// TODO : All users
export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

// TODO : All users
export const ALL_DOCTORS_REQUEST = "ALL_DOCTORS_REQUEST";
export const ALL_DOCTORS_SUCCESS = "ALL_DOCTORS_SUCCESS";
export const ALL_DOCTORS_FAIL = "ALL_DOCTORS_FAIL";

export const CHANGE_DOCTOR_ACCOUNT_STATUS_REQUEST =
  "CHANGE_DOCTOR_ACCOUNT_STATUS_REQUEST";
export const CHANGE_DOCTOR_ACCOUNT_STATUS_SUCCESS =
  "CHANGE_DOCTOR_ACCOUNT_STATUS_SUCCESS";
export const CHANGE_DOCTOR_ACCOUNT_STATUS_FAIL =
  "CHANGE_DOCTOR_ACCOUNT_STATUS_FAIL";
export const CHANGE_DOCTOR_ACCOUNT_STATUS_RESET =
  "CHANGE_DOCTOR_ACCOUNT_STATUS_RESET";

// TODO : clearing the  admin errors
export const ADMIN_CLEAR_ERRORS = "ADMIN_CLEAR_ERRORS";
