// TODO : doctor profile constants
export const DOCTOR_PROFILE_REQUEST = "DOCTOR_PROFILE_REQUEST";
export const DOCTOR_PROFILE_SUCCESS = "DOCTOR_PROFILE_SUCCESS";
export const DOCTOR_PROFILE_FAIL = "DOCTOR_PROFILE_FAIL";

// TODO : Update the doctor Profile
export const UPDATE_DOCTOR_PROFILE_REQUEST = "UPDATE_DOCTOR_PROFILE_REQUEST";
export const UPDATE_DOCTOR_PROFILE_SUCCESS = "UPDATE_DOCTOR_PROFILE_SUCCESS";
export const UPDATE_DOCTOR_PROFILE_FAIL = "UPDATE_DOCTOR_PROFILE_FAIL";
export const UPDATE_DOCTOR_PROFILE_RESET = "UPDATE_DOCTOR_PROFILE_RESET";

export const DOCTOR_APPOINTMENTS_REQUEST = "DOCTOR_APPOINTMENTS_REQUEST";
export const DOCTOR_APPOINTMENTS_SUCCESS = "DOCTOR_APPOINTMENTS_SUCCESS";
export const DOCTOR_APPOINTMENTS_FAIL = "DOCTOR_APPOINTMENTS_FAIL";

export const UPDATE_APPOINTMENT_STATUS_REQUEST =
  "UPDATE_APPOINTMENT_STATUS_REQUEST";
export const UPDATE_APPOINTMENT_STATUS_SUCCESS =
  "UPDATE_APPOINTMENT_STATUS_SUCCESS";
export const UPDATE_APPOINTMENT_STATUS_FAIL = "UPDATE_APPOINTMENT_STATUS_FAIL";
export const UPDATE_APPOINTMENT_STATUS_RESET =
  "UPDATE_APPOINTMENT_STATUS_RESET";

// TODO : for clearing doctor related errors
export const DOCTOR_CLEAR_ERRORS = "DOCTOR_CLEAR_ERRORS";
