// TODO : when the user request for login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// TODO : when the user request for Request
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// TODO : whenever the page is load it will check the user is login or not
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// TODO : for logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// TODO : for refresh the user
export const REFRESH_USER_REQUEST = "REFRESH_USER_REQUEST";
export const REFRESH_USER_SUCCESS = "REFRESH_USER_SUCCESS";
export const REFRESH_USER_FAIL = "REFRESH_USER_FAIL";

// TODO : applying for doctor post
export const APPLY_DOCTOR_REQUEST = "APPLY_DOCTOR_REQUEST";
export const APPLY_DOCTOR_SUCCESS = "APPLY_DOCTOR_SUCCESS";
export const APPLY_DOCTOR_FAIL = "APPLY_DOCTOR_FAIL";
export const APPLY_DOCTOR_RESET = "APPLY_DOCTORRESET";

// TODO : changing unread notifications to read notification
export const CHANGE_UNREAD_NOTI_REQUEST = "CHANGE_UNREAD_NOTIFICATION_REQUEST";
export const CHANGE_UNREAD_NOTI_SUCCESS = "CHANGE_UNREAD_NOTIFICATION_SUCCESS";
export const CHANGE_UNREAD_NOTI_FAIL = "CHANGE_UNREAD_NOTIFICATION_FAIL";
export const CHANGE_UNREAD_NOTI_RESET = "CHANGE_UNREAD_NOTIFICATION_RESET";

// TODO : delete the notification
export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";
export const DELETE_NOTIFICATION_RESET = "DELETE_NOTIFICATION_RESET";

// TODO : all approved doctors
export const ALL_APPROVED_DR_REQUEST = "ALL_APPROVED_DR_REQUEST";
export const ALL_APPROVED_DR_SUCCESS = "ALL_APPROVED_DR_SUCCESS";
export const ALL_APPROVED_DR_FAIL = "ALL_APPROVED_DR_FAIL";

// TODO : single Doctor Detail
export const SINGLE_DOCTOR_DETAIL_REQUEST = "SINGLE_DOCTOR_DETAIL_REQUEST";
export const SINGLE_DOCTOR_DETAIL_SUCCESS = "SINGLE_DOCTOR_DETAIL_SUCCESS";
export const SINGLE_DOCTOR_DETAIL_FAIL = "SINGLE_DOCTOR_DETAIL_FAIL";

// TODO : booking  an appointment
export const BOOK_APPOINTMENT_REQUEST = "BOOK_APPOINTMENT_REQUEST";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_FAIL = "BOOK_APPOINTMENT_FAIL";
export const BOOK_APPOINTMENT_RESET = "BOOK_APPOINTMENT_RESET";

// TODO : check Appointments is available or not
export const CHECK_APPOINTMENTS_REQUEST = "CHECK_APPOINTMENTS_REQUEST";
export const CHECK_APPOINTMENTS_SUCCESS = "CHECK_APPOINTMENTS_SUCCESS";
export const CHECK_APPOINTMENTS_FAIL = "CHECK_APPOINTMENTS_FAIL";
export const CHECK_APPOINTMENTS_RESET = "CHECK_APPOINTMENTS_RESET";
export const CHECK_APPOINTMENTS_CLEAR = "CHECK_APPOINTMENTS_CLEAR";

// TODO : users all appointments
export const USER_APPOINTMENTS_REQUEST = "USER_APPOINTMENTS_REQUEST";
export const USER_APPOINTMENTS_SUCCESS = "USER_APPOINTMENTS_SUCCESS";
export const USER_APPOINTMENTS_FAIL = "USER_APPOINTMENTS_FAIL";

// TODO : for clearing all the errors
export const USER_CLEAR_ERRORS = "USER_CLEAR_ERRORS";
